### ISSUE TITLE
Passphrase Option Disabled When Updating to 1.0.27

### ISSUE THREAD

**Issue by owainedwards80** [Blockstream/Jade#116]
I had a Jade setup to enter a passphrase when opening. After updating to 1.0.27 the passphrase was no longer available. It goes straight to session without any option to enter passphrase. I will have to restore from seed.

**Comment by JamieDriver** [comment]
I'm not sure what version you upgraded from - but that options should certainly not have disappeared!

With a jade initialised with a PIN-protected wallet, go:
`Options->BIP39 Passphrase`

You get the option to set the 'when should Jade ask for a passphrase':
Never: Don't ask for a passphrase after PIN entry
Always: Always ask for a passphrase after PIN entry
Once: Ask for passphrase if you try to unlock jade immediately/now, but in general don't (to obscure the fact that you usually use a passphrase)

NOTE: you can also set whether your passphrase is 'Manual' (ie. free text entry) or whether it is restricted to the BIP39 'Wordlist'.

**Comment by JamieDriver** [comment]
Is this option ^ working for you ?  Is the issue resolved ?  Thanks.

**Comment by JamieDriver** [comment]
Closing as believed to be working, and no response from raiser.
