### ISSUE TITLE
Marketing Material and Reviews Refer to Storage if Liquid Assets Out of the box

### ISSUE THREAD

**Issue by jadenewbie** [Blockstream/Jade#12]
Marketing Material and Reviews Refer to Storage if Liquid Assets Out of the box, Including Liquid Tether.
I find this to be not true. Not sure if this is the place to share that information. Liquid Bitcoin Seems to be the only Green Wallet supported liquid asset.

**Comment by JamieDriver** [comment]
I'm not sure I fully understand.
If you have been sent Liquid assets and they are visible in your wallet, Jade should be able to sign transactions spending those assets.
What issue do you experience ?

**Comment by JamieDriver** [comment]
Closing as no response - please reopen if you believe there is still an issue here.
