### ISSUE TITLE
Electrum package of arch linux is currently incompatible with jade

### ISSUE THREAD

**Issue by 1-21gigasats** [Blockstream/Jade#130]
The electrum wallet package [shipped with arch linux](https://archlinux.org/packages/extra/any/electrum/) is currently incompatible with the jade. The reason is that electrums python-cbor version is [pinned to version 1.0.0](https://github.com/spesmilo/electrum/blob/5f95d919dfa9868eaf82889903b94faa8c6443e0/contrib/requirements/requirements-hw.txt#L27)  while arch only [ships cbor2](https://archlinux.org/packages/extra/x86_64/python-cbor2/).

To get my jade working on arch i did the following.

Installed arch packages:

    electrum python-cbor2 python-pyserial

Changed import of cbor in [jade.py](https://github.com/spesmilo/electrum/blob/5f95d919dfa9868eaf82889903b94faa8c6443e0/electrum/plugins/jade/jadepy/jade.py#L1) to:

    import cbor2 as cbor

So i think to get jade working for everyone on arch two things need to be done:

1. create a patch on electrum to install and use cbor2
2. let arch package maintainers add python-cbor2 and python-pyserial as optional dependency for jade wallet

**Comment by JamieDriver** [comment]
Jade should be updated to use cbor2 already.  Which version of jade / jadepy are you using ?

If you look in this repo you should see:
https://github.com/Blockstream/Jade/blob/0a2ae86be830059457d5710d7e89d641d0d8b23b/requirements.txt#L4
and:
https://github.com/Blockstream/Jade/blob/0a2ae86be830059457d5710d7e89d641d0d8b23b/jadepy/jade.py#L1
...

It has been this way since version `1.0.23` - not sure which version you are using ?
( See: cedab2a0609b18e8b664da44eb9a6e208e388069)

**Comment by JamieDriver** [comment]
Ahh, it looks like electrum is still using an old jade api, `v0.1.37`.  
I will make a PR on electrum to update.

**Comment by 1-21gigasats** [comment]
Sorry for the misleading description. As you mentioned my issue is about the jade version bundled within electrum. Once this version is updated i can offer to let the arch maintainer update the python requirements

**Comment by JamieDriver** [comment]
Looks like above PR merged into Electrum master.  ofc have to await their release proper ...
https://github.com/spesmilo/electrum/pull/9007#issuecomment-2057430133

**Comment by JamieDriver** [comment]
We aim to please!  :laughing: 

Thanks for the heads-up/pointer/reminder.  And of course many thanks to @spesmilo on the Electrum end.  :+1:
