### ISSUE TITLE
No lock when connecting to power supply

### ISSUE THREAD

**Issue by Tacitoku** [Blockstream/Jade#145]
For those who use Jade exclusively in air-gapped mode: 
It would be great if Jade would stay unlocked when a power pack is connected via USB to ensure power supply to Jade. 
The same applies when Jade is connected from a PC via a USB charging cable without a data line.

**Comment by JamieDriver** [comment]
Doesn't seem unreasonable, will give it some thought...  Thanks.

**Comment by JamieDriver** [comment]
This will be included in the next fw release `1.0.31` :+1:

**Comment by Tacitoku** [comment]
Wow - that's great!
Thank you.  👏

**Comment by JamieDriver** [comment]
Should work as you request as of newly released `1.0.31`.

**Comment by Tacitoku** [comment]
Great work! This makes using Jade in pure air-gapped mode much more convenient.

**Comment by JamieDriver** [comment]
^ Many thanks for the suggestion!
