### ISSUE TITLE
Jade crashes when attempting to select 24 words BIP85 with index # > 1230

### ISSUE THREAD

**Issue by totallynarwhal** [Blockstream/Jade#149]
On firmware 1.0.30, when I attempt to use a 24 words BIP85 index # greater than 1230, it crashes the Jade device resulting in a reboot.

Repro steps:
1. Select manual BIP39 Passphrase with Frequence Once
2. QR Pin Unlock with Blockstream's blind oracle, i.e. blkstrm.com/pn
3. Enter Passphrase to start session
4. Go to Wallet->BIP85 and choose 24 Words option
5. Use jog-wheel to increment index # towards 2000

[Expected]
I'm able to navigate and select a BIP85 index that's fairly large, i.e. 2000

[Actual]
When I navigate to ~1230, if I continue to press and hold the jog-wheel, I'll start to get garbled text in the ones and then attempting to increment the index further would then crash and reboot the device.

<img width="910" alt="image" src="https://github.com/user-attachments/assets/58cbb8fb-5fe1-41c8-a732-09d40478fdda">

Note: This seems to only be an issue when holding down the jog-wheel, it appears that I was still able to slowly increment the index if I push the jog-wheel right but not hold. But this means I don't have the ability to fast increment! I'm still pretty far away from index 2000 :(

**Comment by totallynarwhal** [comment]
On a related note - having to use the jog-wheel to manually incremental the index # 1-by-1 is also pretty tedious..

**Comment by JamieDriver** [comment]
Yes, not sure what's going on there - maybe the wheel is generating events faster than they are being consumed and so eventually we run out of [some sort of] RAM or similar.  I'll try to reproduce.

Definitely agree a better way to enter large index #'s is needed.

**Comment by JamieDriver** [comment]
Will investigate using the 'pin-entry' type screens... ie. where you set each digit in turn

**Comment by JamieDriver** [comment]
eg:

![IMG_20240820_165913279](https://github.com/user-attachments/assets/725daf24-239f-4eff-be1c-108d4fa89905)

**Comment by JamieDriver** [comment]
Will switch to above for next fw release `1.0.32`

**Comment by totallynarwhal** [comment]
Updated to allow index up to 999999 as well - awesome!
