### ISSUE TITLE
Nothing happen after approving the bluetooth pairing on both devices

### ISSUE THREAD

**Issue by Transisto** [Blockstream/Jade#16]
I've tried tapping "accept" on the jade first, vise versa, both at once.
Never gets anywhere next.

Android 11

**Comment by Transisto** [comment]
Have the same problem on new phone, also a samsung, S21

**Comment by JamieDriver** [comment]
Is this still an issue ?

**Comment by JamieDriver** [comment]
Closing as no comms for 18mo.
