### ISSUE TITLE
Jade only charges on Pixel 4c running GrapheneOS

### ISSUE THREAD

**Issue by btcpuertorico** [Blockstream/Jade#17]
Connected via USB-C to USB-C cables (more than one), no data exchange, only charges. Tried with different Jade device also, same behavior.

**Comment by Transisto** [comment]
couldn't see it via bluetooth either, look like it could be a protection in the OS somewhere.

**Comment by JamieDriver** [comment]
Is this resolved ?  I know some work was being on the green/android app for Pixel devices in general - but agree the Graphene OS may have tighter protections at the OS level.  (If it is this, there may not be a lot we can do to address - but it will at least be raised/investigated/noted.)

**Comment by btcpuertorico** [comment]
Hey! Yes, it's resolved.

**Comment by JamieDriver** [comment]
Thanks for confirming.
