### ISSUE TITLE
Jade not found during BLE discovery on iOS

### ISSUE THREAD

**Issue by btcpuertorico** [Blockstream/Jade#18]
Jade is not found when trying to pair via BLE on iOS as described on installation guide. Tried two different Jade devices, same behavior.

**Comment by Transisto** [comment]
Jade is not yet supported on iOS, the wireless hardware wallet that you see is currently for Ledger X

**Comment by btcpuertorico** [comment]
What about this guide? https://help.blockstream.com/hc/en-us/articles/900004040226-Blockstream-Jade-Quickstart-Guide#h_01EYXHZ49AV7HP622MCS65VP1Y

**Comment by jgriffiths** [comment]
Jade is supported in https://github.com/Blockstream/green_ios/releases/tag/release_3.5.1 which should reach the app store soon.

**Comment by max302** [comment]
I have just setup Jade successfully on iOS using Green 3.5.1, which is the current version on the app store. 

Had to try the setup three times, but it is working. Can OP confirm?
