### ISSUE TITLE
Jade showed the change address as the first one output, why even show the change if it's in the same XPUB?

### ISSUE THREAD

**Issue by Transisto** [Blockstream/Jade#20]
This is very confusing for new users.

**Comment by JamieDriver** [comment]
Hi,
Jade is not supposed to require the user confirm the change output - if it recognises that it is change.
Can you provide details on how you saw this - in particular what companion app you were using ?
Thanks.

**Comment by Georgantas** [comment]
I noticed the change address needs to be confirmed for CSV/Multisig Shield outputs.

**Comment by JamieDriver** [comment]
It shouldn't ... but it does rely on the companion application indicating which output is change and providing the key derivation path(s) used to build the redeem script - can you confirm the companion app you were using ?

fyi: If the change info is passed, either a) it is correct and the user does not need to confirm change output, or b) it is incorrect and the call should error.
Only if the change data is NOT passed at all, is the user asked to confirm that output - so this rather suggests something missing in what the companion application is passing to Jade.

**Comment by Georgantas** [comment]
Thank you, that makes sense.

I'm asked to confirm the change on the iOS Green app. It must not be passing the metadata. I do not experience this issue using the Green desktop app on Linux.

**Comment by JamieDriver** [comment]
Thanks - I will discuss with the ios guys, cheers.

**Comment by JamieDriver** [comment]
Hi,
I believe this has been addressed in ios release `3.7.9`' (of the Green wallet app).
Please reopen this item if this is not the case.
Many thanks.

**Comment by Georgantas** [comment]
Yep, can confirm it's resolved now. Thank you!
