### ISSUE TITLE
Jade frequently becomes unresponsive when using the scroll wheel

### ISSUE THREAD

**Issue by MHaan91** [Blockstream/Jade#25]
I've had multiple times that I was entering my seed words that it froze and had to restart the process all over because it stayed unresponsive untill a reset.

**Comment by jaamarks** [comment]
@JamieDriver, I have not noticed any issues since updating either.

**Comment by JamieDriver** [comment]
Many thanks, closing issue.

**Comment by jaamarks** [comment]
The wheel sticking seems to be fixed. Though today I was attempting an emergency restore for a wallet and made it through ~22 words and then the Jade went blank and restarted. Not sure if this would be considered a new issue though.

**Comment by JamieDriver** [comment]
There's been some work recently on trying to track down and address rare/random/racy issues relating to the gui-screens and button-events - these fixes will be included in the next fw update.
We've also bumped to the next version of the underlying esp-idf firmware/toolchain - so I'm hoping the next release will bring a lot of stability improvements (even if not so much in the way of new functionality).
