### ISSUE TITLE
Does the Jade check the existence of a change address in the output of a transaction?

### ISSUE THREAD

**Issue by Georgantas** [Blockstream/Jade#29]
This is a continuation of the thread from: https://github.com/Blockstream/Jade/issues/22#issuecomment-1002091796 . I had referenced this article: https://shiftcrypto.ch/blog/the-pitfalls-of-multisig-when-using-hardware-wallets/

I see that the Jade checks that the multisig change address in the output of the transaction is registered on the device: https://github.com/Blockstream/Jade/blob/master/main/process/sign_tx.c#L87

I was wondering though: Does it also check the _existence_ of a change address in the output of a send transaction? I noticed that the Jade will ask the user confirm the change address, but the user has no way of knowing that this address is a "change" address. I'm thinking of the scenario where a malicious computer sends a send-to-many transaction to the Jade, where the second output is not a change address, but an address controlled by the hacker. Can this happen?

**Comment by Georgantas** [comment]
Actually, based on [this](https://github.com/Blockstream/Jade/issues/20#issuecomment-814934215) comment, it seems SingleSig/regular MultiSig change does not need to be confirmed by the user (I was checking MultiSig Shield change).

In that case, can a malicious computer omit the change address completely causing the user to burn the change they should have gotten?

**Comment by JamieDriver** [comment]
At the moment, no - it does not verify or mandate the presence of a change output.

**Comment by Georgantas** [comment]
Makes sense, I forgot the Jade asks the user to confirm the fee 🤦‍♂️ Thank you :)
