### ISSUE TITLE
Button A (previous) not responding on M5 stack

### ISSUE THREAD

**Issue by odudex** [Blockstream/Jade#3]
I set the environment, compiled and flashed Jade on a standard M5 stack and soon noticed Button A was not responding.
I tried to debug input.c and tinker with the code but didn't manage to find out why "btn_handle_prev" was not responding and "button_A" was not being called.
Log warned about "handler already registered, overwriting" but I wasn't able to find out if it has to do with this issue

**Comment by greenaddress** [comment]
hi @odudex this has been fixed in master

Feel free to reopen if you find some issue. thanks!

**Comment by odudex** [comment]
Working now, thanks! Will move on testing it now.
