### ISSUE TITLE
Website OS supports need to be updated

### ISSUE THREAD

**Issue by Transisto** [Blockstream/Jade#34]
From, https://store.blockstream.com/product/blockstream-jade/

Currently:  `Blockstream Green for Android (iOS, Windows, macOS, and Linux support coming soon)`

Sound like it's only supported on Android, while I know it is on iOS

**Comment by Transisto** [comment]
I understand an Android device with a cable seems to be required to update the firmware though.

**Comment by JamieDriver** [comment]
It isn't that it's "required" afaik - it's just that an OTA over BLE is far slower and somewhat prone to error.  
We are working on a solution/mitigation for this at the moment.

Thanks for the reminder about the store notes.

**Comment by alessandro-saglimbeni** [comment]
That's fixed now thanks

**Comment by JamieDriver** [comment]
Closing - Thanks all.
