### ISSUE TITLE
CSV change not being detected using iOS companion app

### ISSUE THREAD

**Issue by Georgantas** [Blockstream/Jade#35]
It seems the issue described [here](https://github.com/Blockstream/Jade/issues/20#issuecomment-1062076826_) has resurfaced (or I made a mistake when I said it was resolved).

FW version: 0.1.33
iOS App Version: 3.7.9

**Comment by Georgantas** [comment]
Maybe this could be fixed on the Jade's side by having it check some default change paths (like the input path + 1, and the common csv_block times [25920, 51840, 64435])?

Another possible solution is maybe to register CSV accounts on the Jade similar to the multisig implementation? In this approach, if an account is registered with an xPub that isn't Blockstream's, a warning could be displayed during registration.

**Comment by JamieDriver** [comment]
Cheers - will pass this on.
fyi jade should display a warning if the csv value is not in the expected list.

**Comment by JamieDriver** [comment]
Can you try in iOS App Version: 3.8.0 pls.  Many thanks.

**Comment by Georgantas** [comment]
Yep, all good now.

Thank you.
