### ISSUE TITLE
Register CSV accounts on the Jade

### ISSUE THREAD

**Issue by georgantas** [Blockstream/Jade#36]
It would be nice to be able to register CSV accounts on the Jade similar to the multisig implementation. If an account is registered with an xPub that isn't Blockstream's, a warning could be displayed during registration.

I think it would also be more secure because an attacker could pass a non-standard `csv_blocks` parameter, and ask for ransom (not sure if this would trigger a warning currently).

**Comment by JamieDriver** [comment]
fyi jade should display a warning if the csv value is not in the expected list.

**Comment by georgantas** [comment]
I think this should be possible with miniscript descriptors now. I will resolve the issue.
