### ISSUE TITLE
A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header

### ISSUE THREAD

**Issue by kccheung** [Blockstream/Jade#4]
I have got an extra [m5stickc_plus](https://docs.m5stack.com/#/en/core/m5stickc_plus) and [m5stickv](https://docs.m5stack.com/#/en/core/m5stickv), but I failed to flash it using the default sdkconfig come up with the repo. I got the error message as title. Is there any suggested menuconfig / sdkconfig I can reference to flash on these two devices? Thanks.

**Comment by greenaddress** [comment]
Neither of them is compatible with the Jade firmware, but the problem you are having is related to the speed of the serial, try 115200 (but don't try the Jade firmware on them, the m5stickc has an incompatible display as far as I know, and the m5stickv has a different SoC)

Closing, but if you manage to get it working on the m5stickc feel free to open a PR!
