### ISSUE TITLE
How to obtain the bootloader? How to sign files?

### ISSUE THREAD

**Issue by kornpow** [Blockstream/Jade#43]
I followed all the steps to build the firmware, and successfully created a build directory.
After moving the build directory to `/tmp/jade`, I attempted to flash:

```
$ DEVNAME=/dev/ttyACM0 ./flash.sh

Device /dev/ttyACM0 can now be flashed
esptool.py v3.0
Serial port /dev/ttyACM0
Connecting......
Detecting chip type... ESP32
Chip is ESP32-D0WDQ6-V3 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 30:c6:f7:1f:6b:84
Uploading stub...
Running stub...
Stub running...
MAC: 30:c6:f7:1f:6b:84
Hard resetting via RTS pin...
esptool.py v3.0
Serial port /dev/ttyACM0
Connecting.....
Detecting chip type... ESP32
Chip is ESP32-D0WDQ6-V3 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 30:c6:f7:1f:6b:84
Uploading stub...
Running stub...
Stub running...
Manufacturer: 20
Device: 4016
Detected flash size: 4MB
Hard resetting via RTS pin...
usage: esptool write_flash [-h] [--erase-all]
                           [--flash_freq {keep,40m,26m,20m,80m}]
                           [--flash_mode {keep,qio,qout,dio,dout}]
                           [--flash_size FLASH_SIZE]
                           [--spi-connection SPI_CONNECTION] [--no-progress]
                           [--verify] [--encrypt]
                           [--ignore-flash-encryption-efuse-setting]
                           [--compress | --no-compress]
                           <address> <filename> [<address> <filename> ...]
esptool write_flash: error: argument <address> <filename>: [Errno 2] No such file or directory: '/tmp/jade/build/bootloader/bootloader_signed.bin'
```

But there is no bootloader? I dont see it mentioned in the docs, and therefore I'd assume it should be built, but I am not really sure.

I am running the latest tagged version.

Later on...

I was able to build using this command, which DID build the bootloader:
`idf.py build`

I had to update the `flash_jade.sh` script, since the generated outputs arent "signed"
```
esptool.py ${COMMON_ESPTOOL_OPTIONS} --flash_size 4MB \
-u 0x1000 ${FLASHROOT}/build/bootloader/bootloader.bin \
0x9000 ${FLASHROOT}/build/partition_table/partition-table.bin 0xE000 \
${FLASHROOT}/build/ota_data_initial.bin 0x10000 ${FLASHROOT}/build/jade.bin | tee -a ${OUTPUTLOG}
```
(notice bootloader.bin vs bootloader_signed.bin and jade.bin vs jade_signed.bin)

I was able to successfully flash, but now the device doesn't turn on. I still see the device connecting to the serial port, but the display doesnt turn on, and Sparrow wallet is telling me the device is responding with an EOF.

**Comment by kornpow** [comment]
I am doing this with a Blockstream Jade device.

I followed pretty much the steps you said above, and attempted a flash (a week or so ago now), and like I said, Sparrow gives an EOF error.

Now I downloaded Blockstream Green, trying to follow this guide: https://help.blockstream.com/hc/en-us/articles/4408030503577-How-do-I-update-Blockstream-Jade-s-firmware-via-USB-cable-
but Green doesnt seem to see the device. I can still the the devices serial port.

What to do in this weird corner case?

The docs should probably be more clear that the instructions here dont really apply at all for Jade, its kind of confusing since this is the Jade repo. I really didnt want to be compiling a release, I just wanted to flash the firmware manually and not through a First Party app like Blockstream Green.

**Comment by JamieDriver** [comment]
This does sound odd.  I didn't think esptool.py would be able to flash anything to a production device.  
A production Jade unit can only run fw signed by Blockstream.  If somehow un-signed fw has been uploaded this may have damaged the device.  I will investigate further.

While it is not mandatory to use the 'Blockstream Green' app to update production fw, that is by far the easiest way.
It is possible to manually download a (signed) fw from the server and call the relevant apis to upload it to the Jade - but it is not immediately trivial and there are many configurations of fw to choose from, eg. for different revisions of the hw.

I will add (and document) some python scripts to facilitate manual two-step (ie download fw file, then upload/update) fw upgrdaes shortly. (It is possible with the existing `jade_ota.py` script, but as that is more of a test tool than an end-user tool, it is not particularly user-friendly.)

(NOTE: It is also possible to build the fw from source to reassure yourself that the signed/provided fw is indeed consistent with the source code tagged in this repo - instructions in progress - see https://github.com/Blockstream/Jade/pull/38)

**Comment by kornpow** [comment]
Thank you! If you can just provide the signed firmware download links, I can try flashing in the same way that I did previously.

**Comment by JamieDriver** [comment]
That's not quite how it works.
The normal fw update process is called 'OTA', and it is a function available in a working fw.
We call a particular api on the jade interface, and we upload a compressed fw file (or fw delta/patch) which it is able to apply.  Then the unit restarts and boots the updated fw.  It does not update the bootloader in any way.

What we are talking about here is flashing a 'virgin' device 'from outside'.  ie. not using a function in the running fw.  (This is not supposed to be available in a production jade unit - but from your description above that is what has occurred.)
The normal compressed fw images will not be suitable - and also you will need a new bootloader.

I should, however, be able to locate suitable files (as they would have been used to create the usual compressed fw images).

**Comment by JamieDriver** [comment]
Sorry - quick question - when you received the Jade device and initially turned it on - did it start up with a pre-installed firmware ?  ie. it started, showed the 'Jade' splash-screen, and then went to a screen with a large 'Initialize' button ?

**Comment by kornpow** [comment]
Yes it had 1.3.2 on it, I was able to generate a seed.

**Comment by JamieDriver** [comment]
I can email you the files in question - although I'm not sure it will work...

Can you run either of these commands against your jade ?  `espefuse.py summary`, or `esptool.py chip_id` ... ?

**Comment by kornpow** [comment]
```
$ esptool.py chip_id
esptool.py v3.0
Found 1 serial ports
Serial port /dev/ttyACM0
Connecting....
Detecting chip type... ESP32
Chip is ESP32-D0WDQ6-V3 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 30:c6:f7:1f:6b:84
Uploading stub...
Running stub...
Stub running...
Warning: ESP32 has no Chip ID. Reading MAC instead.
MAC: 30:c6:f7:1f:6b:84
Hard resetting via RTS pin...
```

I couldnt do `espefuse.py summary`, I got this error: `serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'`

**Comment by JamieDriver** [comment]
Sorry: `espefuse.py --port /dev/ttyACM0 summary`  (not sure why some commands correctly detect the relevant serial port/device, and some don't ...)

**Comment by kornpow** [comment]
```
$ espefuse.py --port /dev/ttyACM0 summary
Connecting....
Detecting chip type... ESP32
espefuse.py v3.0
EFUSE_NAME (Block)                       Description  = [Meaningful Value] [Readable/Writeable] (Hex Value)
----------------------------------------------------------------------------------------
Calibration fuses:
BLK3_PART_RESERVE (BLOCK0):              BLOCK3 partially served for ADC calibration data   = False R/W (0b0)
ADC_VREF (BLOCK0):                       Voltage reference calibration                      = 1121 R/- (0b00011)

Config fuses:
XPD_SDIO_FORCE (BLOCK0):                 Ignore MTDI pin (GPIO12) for VDD_SDIO on reset     = False R/W (0b0)
XPD_SDIO_REG (BLOCK0):                   If XPD_SDIO_FORCE, enable VDD_SDIO reg on reset    = False R/W (0b0)
XPD_SDIO_TIEH (BLOCK0):                  If XPD_SDIO_FORCE & XPD_SDIO_REG                   = 1.8V R/W (0b0)
CLK8M_FREQ (BLOCK0):                     8MHz clock freq override                           = 49 R/W (0x31)
SPI_PAD_CONFIG_CLK (BLOCK0):             Override SD_CLK pad (GPIO6/SPICLK)                 = 0 R/W (0b00000)
SPI_PAD_CONFIG_Q (BLOCK0):               Override SD_DATA_0 pad (GPIO7/SPIQ)                = 0 R/W (0b00000)
SPI_PAD_CONFIG_D (BLOCK0):               Override SD_DATA_1 pad (GPIO8/SPID)                = 0 R/W (0b00000)
SPI_PAD_CONFIG_HD (BLOCK0):              Override SD_DATA_2 pad (GPIO9/SPIHD)               = 0 R/W (0b00000)
SPI_PAD_CONFIG_CS0 (BLOCK0):             Override SD_CMD pad (GPIO11/SPICS0)                = 0 R/W (0b00000)
DISABLE_SDIO_HOST (BLOCK0):              Disable SDIO host                                  = False R/W (0b0)

Efuse fuses:
WR_DIS (BLOCK0):                         Efuse write disable mask                           = 385 R/W (0x0181)
RD_DIS (BLOCK0):                         Efuse read disable mask                            = 1 R/- (0x1)
CODING_SCHEME (BLOCK0):                  Efuse variable block length scheme                
   = NONE (BLK1-3 len=256 bits) R/W (0b00)
KEY_STATUS (BLOCK0):                     Usage of efuse block 3 (reserved)                  = False R/W (0b0)

Identity fuses:
MAC (BLOCK0):                            Factory MAC Address                               
   = 30:c6:f7:1f:6b:84 (CRC 0x25 OK) R/W 
MAC_CRC (BLOCK0):                        CRC8 for factory MAC address                       = 37 R/W (0x25)
CHIP_VER_REV1 (BLOCK0):                  Silicon Revision 1                                 = True R/W (0b1)
CHIP_VER_REV2 (BLOCK0):                  Silicon Revision 2                                 = True R/W (0b1)
CHIP_VERSION (BLOCK0):                   Reserved for future chip versions                  = 2 R/W (0b10)
CHIP_PACKAGE (BLOCK0):                   Chip package identifier                            = 0 R/W (0b000)
MAC_VERSION (BLOCK3):                    Version of the MAC field                           = 0 R/W (0x00)

Security fuses:
FLASH_CRYPT_CNT (BLOCK0):                Flash encryption mode counter                      = 127 R/W (0b1111111)
UART_DOWNLOAD_DIS (BLOCK0):              Disable UART download mode (ESP32 rev3 only)       = False R/W (0b0)
FLASH_CRYPT_CONFIG (BLOCK0):             Flash encryption config (key tweak bits)           = 15 R/W (0xf)
CONSOLE_DEBUG_DISABLE (BLOCK0):          Disable ROM BASIC interpreter fallback             = True R/W (0b1)
ABS_DONE_0 (BLOCK0):                     Secure boot V1 is enabled for bootloader image     = False R/W (0b0)
ABS_DONE_1 (BLOCK0):                     Secure boot V2 is enabled for bootloader image     = True R/W (0b1)
JTAG_DISABLE (BLOCK0):                   Disable JTAG                                       = True R/W (0b1)
DISABLE_DL_ENCRYPT (BLOCK0):             Disable flash encryption in UART bootloader        = True R/W (0b1)
DISABLE_DL_DECRYPT (BLOCK0):             Disable flash decryption in UART bootloader        = True R/W (0b1)
DISABLE_DL_CACHE (BLOCK0):               Disable flash cache in UART bootloader             = True R/W (0b1)
BLOCK1 (BLOCK1):                         Flash encryption key                              
   = ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? -/- 
BLOCK2 (BLOCK2):                         Secure boot key                                   
   = 96 bf 3b 2e 84 0d c9 d7 4f f8 ff fe 2c a4 3f 95 d1 36 2a 1b 18 60 50 64 20 53 1f ae 72 42 f4 f7 R/- 
BLOCK3 (BLOCK3):                         Variable Block 3                                  
   = 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 R/W 

Flash voltage (VDD_SDIO) determined by GPIO12 on reset (High for 1.8V, Low/NC for 3.3V).
```

**Comment by JamieDriver** [comment]
If you want to give me an email address I can send you the files - but I have to confess I am not hopeful that it will work.
I am most puzzled (and concerned) that `esptool.py` and `espfuse.py` were able to connect to your device.

**Comment by kornpow** [comment]
`korn94sam@gmail.com`

**Comment by kornpow** [comment]
Im making progress!
```
Writing at 0x0007fc00... (41 %)
Writing at 0x00080000... (41 %)
Writing at 0x00080400... (41 %)
Writing at 0x00080800... (41 %)
Writing at 0x00080c00... (41 %)
Writing at 0x00081000... (41 %)
Writing at 0x00081400... (41 %)
Writing at 0x00081800... (41 %)
Writing at 0x00081c00... (41 %)
Writing at 0x00082000... (41 %)
Writing at 0x00082400... (41 %)
Writing at 0x00082800... (42 %)
Writing at 0x00082c00... (42 %)
Writing at 0x00083000... (42 %)
Writing at 0x00083400... (42 %)
Writing at 0x00083800... (42 %)
Writing at 0x00083c00... (42 %)
Writing at 0x00084000... (42 %)
Writing at 0x00084400... (42 %)
Writing at 0x00084800... (42 %)
Writing at 0x00084c00... (42 %)

A fatal error occurred: Invalid head of packet (0x10)
```

```
Hash of data verified.
Erasing flash...
Took 0.06s to erase flash block
Writing at 0x0000e000... (12 %)
Writing at 0x0000e400... (25 %)
Writing at 0x0000e800... (37 %)
Writing at 0x0000ec00... (50 %)
Writing at 0x0000f000... (62 %)
Writing at 0x0000f400... (75 %)
Writing at 0x0000f800... (87 %)
Writing at 0x0000fc00... (100 %)
Wrote 8192 bytes at 0x0000e000 in 0.2 seconds (294.2 kbit/s)...
Hash of data verified.
Erasing flash...
Took 2.96s to erase flash block
Writing at 0x00010000... (0 %)
Writing at 0x00010400... (0 %)
Writing at 0x00010800... (0 %)
Writing at 0x00010c00... (0 %)
Writing at 0x00011000... (0 %)
Writing at 0x00011400... (0 %)
Writing at 0x00011800... (0 %)
Writing at 0x00011c00... (0 %)
Writing at 0x00012000... (0 %)
Writing at 0x00012400... (0 %)
Writing at 0x00012800... (1 %)
Writing at 0x00012c00... (1 %)

A fatal error occurred: Timed out waiting for packet header
```

**Comment by kornpow** [comment]
Any news on this?

Can I maybe get a properly "locked down" jade re-sent to me?

**Comment by JamieDriver** [comment]
I'll pass you to the relevant people.  
Did you just buy this unit from the regular store ?

**Comment by bitcoinhelp** [comment]
> Any news on this?
> 
> Can I maybe get a properly "locked down" jade re-sent to me?

Would you mind submitting a ticket on help.blockstream.com? Please reference this issue and provide your order number

**Comment by kornpow** [comment]
I created a ticket

**Comment by JamieDriver** [comment]
Hi - was this resolved ?
