### ISSUE TITLE
Help webcams on QR sign by modifying QR density and changing speed as options on device

### ISSUE THREAD

**Issue by Ciugam** [Blockstream/Jade#50]
As I mentioned above, can you please implement this in the future? Maybe you can help some 720p webcams which have not high fps rate and autofocus. Thanks

**Comment by bitcoinhelp** [comment]
Thanks for your report. Jade actually does support density and frame rate options on the PSBT export screen (under "options")

Are you referring to having these settings for the xpub QRs as well?

**Comment by bitcoinhelp** [comment]
Would you mind scanning a PSBT so you can get into the Options settings and change to low density? Then you can return back to the xpub display and it will use the low density as well.

Just curious if your camera is able to pick up the Low option

**Comment by odudex** [comment]
Sorry to interrupt with dirty hacks but they may be useful while something more neat is no available. (I'm no from Blockstream, just a Jade admirer).
- Place a convex lens, like a magnifying glass in front of  computer's camera, it will move focal point to a closer region(macro)
- Place a white paper behind Jade so computer's camera lower sensitivity and don't saturate QR image

**Comment by bitcoinhelp** [comment]
> I'll explain better: actually on the laptop I'm using, the webcam has not autofocus and is 720p with low framerate.
> Example: if I use Jade as air-gapped, I have to export my QR xpub; I cannot because of webcam issue (probably not on focus and very little space available to scan). I haven't signed any transaction as a consequence of that.
> So, my request is: while Jade is showing QRs (any), can you implement some options as "QR density pixels" and "change speed/framerate" to mitigate this issue?

Sorry should have explained. You can either plug in your Jade via USB just to add the wallet so you'll able to sign a psbt, or if you're trying to keep it air-gapped - try using BlueWallet on your mobile device just to try signing a PSBT. That way you'll be able to access the settings. I'm curious if the Low density even works at all for the xpub

**Comment by bitcoinhelp** [comment]
@odudex always coming in with the awesome camera tips 🔥

@Ciugam lmk if those tips help at all

**Comment by bitcoinhelp** [comment]
@Ciugam would you mind changing the settings from the Export PSBT screen to Low and see if that will scan? That will also change the xpub QR settings btw

Please let me know if your webcam is able to scan the Low density xpub/psbt
