### ISSUE TITLE
Feature request - Please add monochrome display option

### ISSUE THREAD

**Issue by danskich** [Blockstream/Jade#57]
There's no option to switch between monochrome or color display. I noticed after several wallets switched from monochrome to color display, it got way brighter and 'tough' on the eyes, especially if you need to do multiple transactions or use the wallet for extended periods of time. Monochrome would be helpful option to have.

**Comment by JamieDriver** [comment]
Not monochrome, but adding a 'screen brightness' setting in fw `0.1.48`, so you can dim the screen to your preferred brightness (side effect - dimming screen should increase battery life).

**Comment by JamieDriver** [comment]
FYI: intend to offer this in the upcoming fw release.  There will be an option to change the highlight colour used - as well as offering other 'bright' colours, there will also be light/dark grey options - selecting one of these should effectively be a 'monochrome mode'.
