### ISSUE TITLE
"Response ID mismatch" error when trying to send

### ISSUE THREAD

**Issue by Transisto** [Blockstream/Jade#6]
![image](https://user-images.githubusercontent.com/388716/105621476-b6ba1e00-5dd5-11eb-9a5e-e49410ead991.png)

Response ID mismatch.

**Comment by JamieDriver** [comment]
Was this an isolated incident or is it reproducible ?

**Comment by JamieDriver** [comment]
Closing as no response, issue not reproducible and in any case from the above suspect was a companion app issue.
