### ISSUE TITLE
Difference between sleep and logout?

### ISSUE THREAD

**Issue by scarolan** [Blockstream/Jade#71]
I couldn't find any info in the FAQ or docs.  What is the difference between putting the device into deep sleep vs using logout?

As far as I can tell the behavior is identical.  To wake the device or power it back on I still have to push the green button and re-enter my PIN.

**Comment by bitcoinhelp** [comment]
Logout won't shut off your device, just bring you back to the "home"/connect Jade screen

**Comment by scarolan** [comment]
So how do you wake it from sleep then?  I tried short presses of each button, the only thing that worked to get the screen back was long-press the green button.

**Comment by scarolan** [comment]
Why is it called 'sleep' and not 'power off'?  Is there even a difference?

**Comment by scarolan** [comment]
Roger that, thanks!  Closing issue.
