### ISSUE TITLE
Change account number to participate in multiple multisigs.

### ISSUE THREAD

**Issue by polto** [Blockstream/Jade#75]
It's currently not possible to change account number. It would be a nice feature to be able to change the derivation path at least for the account level. 

I would like to export a few dozens of XPubs (one per account level) to participate in different segregated multisigs.
In my use case the signing devices are same for all multisigs, I am just segregating them for logical separation of different accounts. 

Later I will want to import multiple multisigs. Hope it will work too.

**Comment by JamieDriver** [comment]
When setting up a multisig on Jade (whether by scanning QR or by accepting a message) Jade should accept any path.
It will then sign (and verify change for) child nodes on that path.

The only place the path/account is fixed, is in the QR Xpub Export.  Agree it's not ideal.

Yes, we could possibly allow setting 'account' (in the same way we set eg. bip85 index).

**Comment by polto** [comment]
I tried with the 1.2.4 green wallet on Linux and the latest mobile app on Android play store.

I can add multiple accounts, but I am not able to export the XPub of that account. Whatever account is selected in the Green Wallet - the XPub Export menu only export the account 0.

It would be really nice to support setting the account level. Options on XPub Export screen are changeable, it would be nice to be able to click on the derivation path and change parts like the account number.

Speaking of selecting a custom derivation path - we would be interested in having support for Blinded XPub. This requires setting a custom derivation path.

**Comment by polto** [comment]
updated jade to the latest 1.0.21. Still can not change the account number. 

Another idea on where to have the option to change the account is in XPub Settings page.

Could you please prioritize this ? we try to use jade in multiple multi-sig accounts.

**Comment by bitcoinhelp** [comment]
You can get whatever account number you want when using Jade via USB, we'll likely add it for QR soon

**Comment by polto** [comment]
OK, so it works only while Jade is used over USB. Would be nice also to be able to use multiple accounts with QR workflow.

**Comment by JamieDriver** [comment]
FYI Planning to include setting account for xpub export, and account and change flag for address qr scan verification in upcoming fw release `1.0.24`.

**Comment by JamieDriver** [comment]
`1.0.24` released - you should now be able to export xpub for any account element, and also scan QR addresses for any account.  
Close this item as resolved.

FYI: using totally bespoke paths is supported via the usb/ble interface - with airgapped use the challenge is more one of nice/usable UI/UX than anything.

Please reopen if you do not believe the headline issue resolved.  Thanks.
