### ISSUE TITLE
"internal error - restarting" when trying to send to p2pkh addresses

### ISSUE THREAD

**Issue by prelude444** [Blockstream/Jade#8]
jade crashes whenever I try to send to a p2pkh address(legacy). Jade will print "internal error - restarting" on its screen and restart as soon as I confirm the transaction info on my android green wallet.  Sending to segwit addresses are working fine, however.

**Comment by greenaddress** [comment]
We are releasing version 0.1.23 which will fix the issue (already fixed in master)

thank you for the report!

**Comment by prelude444** [comment]
is there a user friendly way to update the firmware?

**Comment by JamieDriver** [comment]
Hi,
Can you confirm whether this issue was resolved ?
Thanks.

**Comment by prelude444** [comment]
Yes resolved after firm ware upgradr
-------- Original message --------From: "Jamie C. Driver" ***@***.***> Date: 4/7/21  10:03 AM  (GMT-05:00) To: Blockstream/Jade ***@***.***> Cc: prelude444 ***@***.***>, Author ***@***.***> Subject: Re: [Blockstream/Jade] "internal error - restarting" when trying to send to p2pkh addresses (#8) 
Hi,
Can you confirm whether this issue was resolved ?
Thanks.

**Comment by JamieDriver** [comment]
Many thanks.
