### ISSUE TITLE
Question: API Docs for communication?

### ISSUE THREAD

**Issue by xtools-at** [Blockstream/Jade#81]
Hi, I'm looking into integrating Jade into a wallet I'm working on.
Is there any documentation out there on how to communicate with Jade via USB/BLE/QR? I'm having a hard time reverse-engineering how the protocol is supposed to work just by looking at the firmware code or the Green wallet source.
Since Jade is integrated with a [ton of wallets](https://help.blockstream.com/hc/en-us/articles/9601453403801-Download-a-companion-app-for-Jade) already, is there any guideline or documentation on how to go about that?

**Comment by bitcoinhelp** [comment]
Most wallets use [HWI](https://github.com/bitcoin-core/HWI) to communicate with Jade

Here is an example of us using webserial to talk to Jade
https://github.com/Blockstream/webjadeupgrader

doc for the messages:
https://github.com/Blockstream/Jade/blob/master/docs/index.rst

For QR we just use the [bc-ur](https://github.com/BlockchainCommons/bc-ur)
