### ISSUE TITLE
Passphrase confirmation screen fails to correctly display long passphrases

### ISSUE THREAD

**Issue by rstmsn** [Blockstream/Jade#95]
When a long passphrase is entered, and the user proceeds to the passphrase confirmation screen, rather than using up all of the available space on the screen, the long passphrase is displayed on the first line, and half of the second line, then wraps back to the beginning of the first line, making the initial part of the first line unreadable.

Is it safe to assume that this is a display issue, only? And that the long passphrase has been read / stored correctly?

**Comment by bitcoinhelp** [comment]
Which firmware version are you on? This was fixed in 1.0.23 afaik

**Comment by bitcoinhelp** [comment]
Yep, just a visual issue 👍

**Comment by rstmsn** [comment]
Thanks for the help 😌
