### ISSUE TITLE
What hash is being displayed during the update?

### ISSUE THREAD

**Issue by Giszmo** [Blockstream/Jade#97]
A user asked me to reproduce the latest 1.0.26 for Walletscrutiny and while I could reproduce some firmware I'm not sure what the user has there as the hash displayed on this device does not coincide with any data in https://jadefw.blockstream.com/bin/jade/index.json
Searching for ac2 yields zero results.

![IMG_6358](https://github.com/Blockstream/Jade/assets/96378/10fbd423-37cc-4141-ba2e-2463cbedf7ef)

I'm crossing fingers you guys display some dhash instead of a plain sha256 here but I'm mildly concerned.

Or is it Jade 1.1? In [REPRODUCIBLE.md](REPRODUCIBLE.md) I see four builds referenced - 1.0/1.1, radio yes/no - yet the json only contains two per version. Where can I find the Jade 1.1 binaries?

After not finding "ac28" in https://jadefw.blockstream.com/bin/jade1.1/index.json neither, I'm starting to get more worried ...

**Comment by JamieDriver** [comment]
It can depend what app is being used to upgrade the fw.  
If it is a recent app it should be passing the fw hash out of the index file - this is the hash of the final firmware image (ie. regardless of full/delata update).
In that case the screen would say, 'Fw Hash: ...'

The fact that it says 'File Hash' suggests to me that the app is not passing the hash of the final fw image, but rather the simple sha256 hash of the file it is uploading - this was an earlier iteration designed more to check the file integrity during upload than to verify the fw image.

**Comment by JamieDriver** [comment]
fyi the plan is to make the newer 'full image hash' mandatory during ota at some point soon - atm we are allowing 'grace period' support of the old style.

**Comment by Giszmo** [comment]
So ... I tell the user we have no idea which binary was installed? I see the deltas also have associated hashes. Is the index not complete?

**Comment by JamieDriver** [comment]
I'd be interested to know which application is doing that fw update - is it a Green app and if so which version ?
We really need to ensure all updating apps are using the final uncompressed fw hash - the hash of the fw that will actually run.

Yes, I could include the hash of the compressed files in the index.json - that shouldn't be an issue.

**Comment by hazelblitz** [comment]
Hey @JamieDriver, I am the user in question. This is what I fetched from the log file of my Green app.

[2023-07-31 17:08:16.716716] [app:warning] Detected system locale encoding (US-ASCII, locale "C") is not UTF-8.
Qt shall use a UTF-8 locale ("UTF-8") instead. If this causes problems,
reconfigure your locale. See the locale(1) manual for more information.
[2023-07-31 17:08:16.826826] [app:info] Blockstream Green 1.2.5
[2023-07-31 17:08:16.826826] [app:info] Environment: Production
[2023-07-31 17:08:16.826826] [app:info] System Information:
[2023-07-31 17:08:16.826826] [app:info]   Build ABI: arm64-little_endian-lp64
[2023-07-31 17:08:16.826826] [app:info]   Build CPU Architecture: arm64
[2023-07-31 17:08:16.826826] [app:info]   Current CPU Architecture: arm64
[2023-07-31 17:08:16.826826] [app:info]   Hardware Model: MacBookAir10,1
[2023-07-31 17:08:16.826826] [app:info]   Kernel Type: darwin
[2023-07-31 17:08:16.826826] [app:info]   Kernel Version: 22.5.0
[2023-07-31 17:08:16.826826] [app:info]   Product: macOS 13.4
[2023-07-31 17:08:16.827827] [app:info]   Product Type: macos
[2023-07-31 17:08:16.827827] [app:info]   Product Version: 13.4

**Comment by JamieDriver** [comment]
Hi @hazelblitz, thanks for the detailed info.
I note: `[2023-07-31 17:08:16.826826] [app:info] Blockstream Green 1.2.5`, and I see the latest release (end of September) is `1.2.8`, and moreover on the [release notes for that version](https://github.com/Blockstream/green_qt/releases/tag/release_1.2.8) it says: "Show correct firmware hash when updating Jade" - I suspect that covers both the app screen and the data fields it passes to Jade.

At upgrade time Jade can only show what it has been sent, and then confirm that what is uploaded *really does match* what you were shown.
As mentioned above, we want to show (and verify) the hash of the final uncompressed firmware image, but some apps still send the legacy data, the hash of the file being uploaded.  Jade will still show and then confirm that hash - we just think that it isn't as useful as the final fw hash.  At some point we will make that mandatory - we're just giving people time to upgrade to newer apps before we do that (or upgrade attempts will be rejected altogether).

**Comment by JamieDriver** [comment]
>  I see the deltas also have associated hashes but only of the target FW, not of the patch itself. How about adding this for verifiability? Updating the JSON should be trivial and with almost no negative impact.

This has been done, and will be maintained going forward.
Cheers.

**Comment by JamieDriver** [comment]
I think we have resolved issues here going forward.
Closing - pls reopen if you disagree.  Cheers.

**Comment by eliaspfeffer** [comment]
Reopened it, see: https://github.com/Blockstream/Jade/issues/131

**Comment by JamieDriver** [comment]
Appears to be user checking wrong index file - will leave for @eliaspfeffer to close if agrees.

**Comment by eliaspfeffer** [comment]
@JamieDriver Could you please tell me where to look or a link? Thanks a lot in advance!

**Comment by eliaspfeffer** [comment]
@JamieDriver Thanks, your response in https://github.com/Blockstream/Jade/issues/131 solved it.
